apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: core-app
  template:
    metadata:
      labels:
        app: core-app
    spec:
      containers:
        - name: core
          image: radomkhoem/core_spring:51
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: core-config
              mountPath: /app/access-refresh-token-keys
      volumes:
        - name: core-config
          hostPath:
            path: /home/radomkhoem/core-config
---
apiVersion: v1
kind: Service
metadata:
  name: core-service
spec:
  type: NodePort
  selector:
    app: core-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30012
