# Deployment and Service for Core API with volume
---
apiVersion: apps/v1
kind: Deployment # Specifies that this resource is a Deployment, which ensures a specified number of pod replicas are running at any given time
metadata:
  name: core-app
spec:
  replicas: 3 # Number of pod replicas to maintain
  selector:
    matchLabels:
      app: core-app
  template:
    metadata:
      labels:
        app: core-app
    spec:
      containers:
        - name: core
          image: radomkhoem/core_spring:51
          ports:
            - containerPort: 8080
          volumeMounts: # Mount the volume to the container
            - name: core-config # Name of the volume
              mountPath: /app/access-refresh-token-keys # Path to mount the volume
      volumes:
        - name: core-config # Name of the volume
          hostPath: 
            path: /home/radomkhoem/core-config # Path to the host directory

---
# Create a Service for the Core API
apiVersion: v1
kind: Service
metadata:
  name: core-service
spec:
  type: NodePort
  selector:
    app: core-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30012
