apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs-deployment
  namespace: front-end
  labels:
    app: nextjs-ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nextjs-ui
  template:
    metadata:
      labels:
        app: nextjs-ui
    spec:
      containers:
      - name: nextjs-ui-cont
        image: muyleangin/surveybox-ui:latest
        ports:
        - containerPort: 3000
        resources: # minimum resources required by the container
          limits:
            cpu: "500m" # 0.5 core
            memory: "512Mi" # 512 Mebibytes

---
# Create a LoadBalancer Service to expose the Deployment
apiVersion: v1
kind: Service
metadata:
  name: nextjs-svc # Name of the Service
  namespace: front-end
spec:
  type: LoadBalancer
  selector:
    app: nextjs-ui  
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 30002
