# Deployment: nginx-deployment
# A Deployment provides declarative updates to Pods and ReplicaSets.
---
apiVersion: apps/v1
kind: Deployment  
metadata:
  name: nginx-deployment # Name of the Deployment
spec:
  replicas: 3 # Number of Pods to run
  selector:
    matchLabels:
      app: my-nginx-app # Label to match with the Pod
  template:
    metadata:
      labels:
        app: my-nginx-app  # Label to match with the Pod
    spec:
      containers:
      - name: nginx-ui-cont
        image: nginx:1.22.1
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"  # Maximum amount of CPU that the container can use
            memory: "512Mi" # Maximum amount of memory that the container can use

---
# Create a Service to expose the Deployment
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: my-nginx-app
  ports:
    - protocol: TCP
      port: 81 # Port exposed by the Service
      targetPort: 80 # Port on the container (matches containerPort)
  type: NodePort