--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  strategy:
    type: RollingUpdate 
    rollingUpdate: 
      maxSurge: 1 # Maximum number of Pods that can be created above the desired number of Pods
      maxUnavailable: 1 # Maximum number of Pods that can be unavailable during the update
  selector:
    matchLabels:
      app: nginx-ui 
  template:
    metadata:
      labels:
        app: nginx-ui
    spec:
      containers:
      - name: nginx-ui-cont
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5" # Maximum amount of CPU that the container can use
            memory: "512Mi" # Maximum amount of memory that the container can use
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  type: NodePort
  selector:
    app: nginx-ui  
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30004