
# Pod: Represents a group of one or more containers.
apiVersion: v1
kind: Pod # Kind of the resource(Pod is a resource in k8s cluster which runs a container)
metadata:
  name: nginx-pod   # Name of the pod
  labels:
    app: nginx-lbl  # Label to be used
  namespace: front-end  # Namespace for the pod
spec:
  containers: 
    - name: nginx-cont       # Name of the container
      image: nginx:1.22.1     # Image to be used 
      ports:
        - containerPort: 80   # Port on which the container is listening