# Create a ReplicaSet for the Nginx container
apiVersion: apps/v1
kind: ReplicaSet # Specifies that this resource is a ReplicaSet, which ensures a specified number of pod replicas are running at any given time
metadata:
  name: nginx # Name of the ReplicaSet
  labels:
    app: nginx-ui # Label to be used
spec:
  replicas: 3 # Number of pod replicas to maintain
  selector:
    matchLabels:
      app: nginx-ui # Label to be used
  template:
    metadata:
      labels:
        app: nginx-ui # Label to be used
    spec:
      containers:
      - name: nginx-ui-cont # Name of the container
        image: nginx:latest
        ports:
        - containerPort: 80 # Port on which the container is listening

---
# Create a Service for the Nginx container
apiVersion: v1
kind: Service
metadata:
  name: nginx-ui
spec:
  type: NodePort
  selector:
    app: nginx-ui  # Label to be used (corrected to match the pod label)
  ports:
  - protocol: TCP # The protocol that the service is using
    port: 80
    targetPort: 80
    nodePort: 30003 # The port on the node that is exposed to the service