# Create a ReplicaSet for the Nginx container
apiVersion: apps/v1
kind: ReplicaSet # Kind of the resource(ReplicaSet is a resource in k8s cluster which runs multiple replicas of a pod)
metadata:
  name: nginx-rs # Name of the ReplicaSet
  labels:
    app: nginx-ui 
  namespace: front-end 
spec:
  replicas: 3 # Number of replicas to be maintained
  selector:
    matchLabels:
      app: nginx-ui
  template: # Template for creating the pod
    metadata:
      labels:
        app: nginx-ui
    spec:
      containers:
      - name: nginx-ui-cont 
        image: nginx:latest # Image to be used
        ports:
        - containerPort: 80 # Port on which the container is listening

---
# Create a Service for the Nginx container
apiVersion: v1
kind: Service
metadata:
  name: nginx-ui-svc # Name of the service
  namespace: front-end
spec:
  type: NodePort # Exposes the service on each Node's IP at a static port
  selector:
    app: nginx-ui
  ports:
  - protocol: TCP 
    port: 80 # External port(Can be accessed from outside the cluster)
    targetPort: 80 # Container's internal port(Can be accessed from inside the cluster)
    nodePort: 30003 # Port on which the service is exposed on the Node