apiVersion: v1
kind: Secret
metadata:
  name: medical-app-secret
  namespace: medical-appointment
type: Opaque
data:
  POSTGRES_DB: bWVkaWNhbF9hcHB0X2Ri  # base64 encoded value of 'medical_appt_db'
  POSTGRES_USER: cG9zdGdyZXM=        # base64 encoded value of 'postgres'
  POSTGRES_PASSWORD: YWRtaW5AMTIz     # base64 encoded value of 'admin@123'

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: medical-app-config
  namespace: medical-appointment
data:
  APP_BASE_URI: "http://35.240.198.147:30012/"
  DB_HOST: "35.240.142.204"
  DB_PORT: "8096"
  FILE_BASE_URI: "http://35.240.198.147:30012/file/"
  FILE_DOWNLOAD_URI: "http://35.240.198.147:30012/api/v1/files/download/"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: medical-app
  namespace: medical-appointment
  labels:
    app: medical-app
    environment: production
  annotations:
    description: "Deployment for Medical API"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: medical-app
  template:
    metadata:
      labels:
        app: medical-app
    spec:
      containers:
        - name: medical
          image: radomkhoem/medical_appointment_app:v1.0.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: token-keys
              mountPath: /app/keys
            - name: file-server-path
              mountPath: /opt/app/media/images/
          envFrom:
            - configMapRef:
                name: medical-app-config
            - secretRef:
                name: medical-app-secret
          env:
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: medical-app-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: medical-app-secret
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: medical-app-secret
                  key: POSTGRES_DB
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
      volumes:
        - name: token-keys
          nfs:
            server: 35.240.198.147
            path: /opt/nfs/data/token-keys
        - name: file-server-path
          nfs:
            server: 35.240.198.147
            path: /opt/nfs/data/file-server-path

---
apiVersion: v1
kind: Service
metadata:
  name: medical-service
  namespace: medical-appointment
  labels:
    app: medical-app
spec:
  type: NodePort
  selector:
    app: medical-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30012