
---

# Secret: Stores sensitive data, such as passwords and tokens.
apiVersion: v1
kind: Secret
metadata:
  name: example-secret
  namespace: default
type: Opaque
data:
  username: YWRtaW4=  # base64 encoded value of 'admin'
  password: MWYyZDFlMmU2N2Rm  # base64 encoded value of '1f2d1e2e67df'
