
---
# Service: Exposes a set of Pods as a network service.
apiVersion: v1
kind: Service       # Kind of the resource (Service is a resource in k8s cluster which exposes the pod)
metadata:
  name: nginx-svc   # Name of the service
  namespace: front-end  # Namespace for the service
spec:
  type: NodePort    # Type of the service
  selector:
    app: nginx-lbl  # Label to be used (corrected to match the pod label)
  ports:
    - protocol: TCP
      port: 80          # The pod will listen on port 80 using the TCP protocol.
      targetPort: 80    # Incoming traffic on port 80 will be forwarded to the pod's port 80.
      nodePort: 30080   # The pod's port 80 will be exposed on the cluster's nodes on port 30080.