apiVersion: v1
kind: Pod # Kind of the resource(Pod is a resource in k8s cluster which runs a container)
metadata:
  name: nginx-pod   # Name of the pod
  labels:
    app: nginx-lbl  # Label to be used
  namespace: nginx  # Namespace for the pod
spec:
  containers: 
    - name: nginx-cont        # Name of the container
      image: nginx:1.22.1     # Image to be used 
      ports:
        - containerPort: 80   # Port on which the container is listening
---
apiVersion: v1
kind: Service       # Kind of the resource (Service is a resource in k8s cluster which exposes the pod)
metadata:
  name: nginx-svc   # Name of the service
  namespace: nginx  # Namespace for the service
spec:
  type: NodePort    # Type of the service
  selector:
    app: nginx-lbl  # Label to be used (corrected to match the pod label)
  ports:
    - protocol: TCP
      port: 80          # The pod will listen on port 80 using the TCP protocol.
      targetPort: 80    # Incoming traffic on port 80 will be forwarded to the pod's port 80.
      nodePort: 30080   # The pod's port 80 will be exposed on the cluster's nodes on port 30080.