apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx
  labels:
    app: nginx-ui
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-ui
  template:
    metadata:
      labels:
        app: nginx-ui
    spec:
      containers:
      - name: nginx-ui-cont
        image: nginx:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-svc
spec:
  type: NodePort
  selector:
    app: nginx-ui  
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30003  
